name: FakeBlock
version: 1.4.5
main: com.huskehhh.fakeblock.FakeBlock
author: husK
description: Enables the creation of fake blocks, so only people with the a permission node can walk through.
commands:
  fakeblock:
    description:
    usage:
  fb:
    description:
    usage:
api-version: 1.14