name: FakeBlock
version: 1.4.7
main: com.huskehhh.fakeblock.FakeBlock
author: husK
description: Enables the creation of fake blocks, so only people with the a permission node can walk through.
commands:
  fakeblock:
    description: Shows all available commands
    usage: /<command>
    aliases: [fb]
api-version: 1.14
depend: [ProtocolLib]